version: '3.7'

networks:
  indyscan:
    name: indyscan
    driver: bridge
  esnet:
    name: esnet
    driver: bridge
  vcxnet:
    name: vcxnet
    driver: bridge

volumes:
  indyscan-es:
    driver: local
