version: '3.7'

x-es-logging:
  &es-logging
  options:
    max-size: '300m'
    max-file: '2'
  driver: json-file

services:
  indyscan-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: indyscan-elasticsearch
    logging: *es-logging
    networks:
      - esnet
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - indyscan-es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  indyscan-es:
    driver: local
