version: '3.7'

x-standard-logging:
  &service-logging
  options:
    max-size: '500m'
    max-file: '3'
  driver: json-file

x-ui-logging:
  &ui-logging
  options:
    max-size: '100m'
    max-file: '3'
  driver: json-file

services:
  indyscan-daemon:
    restart: unless-stopped
    image: docker.pkg.github.com/patrik-stas/indyscan/indyscan-daemon:4.5.2-dependenciesvdr-tools-429
    container_name: indyscan-daemon
    logging: *service-logging
    depends_on:
      - indyscan-elasticsearch
    networks:
      - esnet
      - indyscan
    environment:
      - WORKER_CONFIGS=/home/indyscan/indyscan-daemon/app-configs-docker/sovmain.json,/home/indyscan/indyscan-daemon/app-configs-docker/sovstaging.json,/home/indyscan/indyscan-daemon/app-configs-docker/sovbuilder.json
      - LOG_LEVEL=info
      - ENABLE_LOGFILES=false
      - LOG_HTTP_REQUESTS=true
      - LOG_HTTP_RESPONSES=true
      - SERVER_ENABLED=true
      - SERVER_PORT=3709
      - AUTOSTART=true
    ports:
      - 3709:3709
    volumes:
      - ./app-config-daemon/:/home/indyscan/indyscan-daemon/app-configs-docker

  indyscan-daemon-ui:
    restart: unless-stopped
    image: docker.pkg.github.com/patrik-stas/indyscan/indyscan-daemon-ui:4.4.1
    container_name: indyscan-daemon-ui
    logging: *ui-logging
    environment:
      - PORT=3710
      - PROXY_API_URL=http://indyscan-daemon.indyscan:3709
      - CHOKIDAR_USEPOLLING=true
    networks:
      - indyscan
    ports:
      - 3710:3710

  indyscan-api:
    restart: unless-stopped
    image: docker.pkg.github.com/patrik-stas/indyscan/indyscan-api:4.4.1
    container_name: indyscan-api
    logging: *service-logging
    environment:
      - NETWORKS_CONFIG_PATH=/home/indyscan/indyscan-api/app-config-docker/sovrin.json
      - ES_URL=http://indyscan-elasticsearch.esnet:9200
      - LOG_LEVEL=info
      - PORT=3708
      - LOG_HTTP_REQUESTS=true
      - LOG_HTTP_RESPONSES=true
    networks:
      - indyscan
      - esnet
    ports:
      - 3708:3708
    volumes:
      - ./app-config-api/:/home/indyscan/indyscan-api/app-config-docker

  indyscan-webapp:
    restart: unless-stopped
    image: docker.pkg.github.com/patrik-stas/indyscan/indyscan-webapp:4.4.1
    container_name: indyscan-webapp
    logging: *ui-logging
    environment:
      - INDYSCAN_API_URL=http://indyscan-api.indyscan:3708
      - DAEMON_WS_URL=http://indyscan-daemon.indyscan:3709
      - PORT=3707
      - LOG_LEVEL=warn
      - LOG_HTTP_REQUESTS=true
      - LOG_HTTP_RESPONSES=true
      - NODE_ENV=development
    networks:
      - indyscan
    ports:
      - 3707:3707
